# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Application
DESTDIR = .
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += .
UI_DIR += .
RCC_DIR += .
include(Application.pri)
QT += svg
QT += gui
QT += opengl